apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: productdbserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: productdbserver
    spec:
      containers:
      - name: productdbserver
        image: microsoft/mssql-server-linux:latest
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "Password_1234"
        - name: MSSQL_PID
          value: "Developer"