apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: productdbserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: productdbserver
    spec:
      containers:
      - name: productdbserver
        image: mongo:4.0.4
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "root"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "example"